function menuPreferences_Callback(~,~,handles)
% Preferences Menu
% Load and Save changes in Preferences.mat

global SEED SEED_SWL SEED_REGION SEED_CONFIG SEED_ATLAS DIR_SAVE DIR_FIG DIR_STATS DIR_SYNT ;
load('Preferences.mat','GParams','GDisp','GTraces','GImport','GFilt','GColors',...
    'GParams_default','GDisp_default','GTraces_default','GImport_default','GFilt_default','GColors_default','selected_tab');
%if ~exist('selected_tab','var')
%    selected_tab = 'General';
%end

% Display Parameters
W = 100;
H = 50;
ftsize = 10;
panelColor = get(0,'DefaultUicontrolBackgroundColor');

% Creating Dialog Box
f2 = dialog('Units','characters',...
    'Position',[30 30 W H],...
    'HandleVisibility','callback',...
    'IntegerHandle','off',...
    'Renderer','painters',...
    'Toolbar','figure',...
    'NumberTitle','off',...
    'Name','Preferences');

mainPanel = uipanel('FontSize',ftsize,...
    'Units','characters',...
    'Position',[0 6 W H-6],...
    'Parent',f2);
pos = get(mainPanel,'Position');

tabgp = uitabgroup(mainPanel);
tab0 = uitab(tabgp,'Title','General');
tab1 = uitab(tabgp,'Title','Import');
tab2 = uitab(tabgp,'Title','Traces');
tab3 = uitab(tabgp,'Title','Filtering');
tab4 = uitab(tabgp,'Title','Display');
tab5 = uitab(tabgp,'Title','Colors');

% Find selected tab
ind_tab = findobj(tabgp,'Title',selected_tab);
tabgp.SelectedTab = ind_tab;

% Reset & Reset All Buttons
resetparamButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/4 3 W/4 2],...
    'String','Reset',...
    'Parent',f2);

resetAllparamButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/2 3 W/4 2],...
    'String','Reset all',...
    'Parent',f2);

% OK & CANCEL Buttons
okButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/4 1 W/4 2],...
    'String','OK',...
    'Parent',f2);

cancelButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/2 1 W/4 2],...
    'String','Cancel',...
    'Parent',f2);

set(okButton,'Callback',@okButton_callback);
set(cancelButton,'Callback', @cancelButton_callback);
set(resetparamButton,'Callback',@resetparamButton_callback);
set(resetAllparamButton,'Callback',@resetAllparamButton_callback);

    function cancelButton_callback(~,~)
        close(f2);
    end

    function okButton_callback(~,~)
        
        % SEED SEED_SWL sep_swl_1 sep_swl_2 Update
        SEED=get(ui_seed,'String');
        SEED_SWL=get(ui_seed_swl,'String');
        SEED_REGION=get(ui_seed_region,'String');
        SEED_CONFIG=get(ui_seed_config,'String');
        SEED_ATLAS=get(ui_seed_atlas,'String');
        DIR_SAVE=get(ui_dir_save,'String');
        DIR_FIG=get(ui_dir_fig,'String');
        DIR_STATS=get(ui_dir_stats,'String');
        DIR_SYNT=get(ui_dir_synt,'String');
        
        % Display parameters Update
        GDisp.W = str2double(get(ui_W,'String'));
        GDisp.H = str2double(get(ui_H,'String'));
        GDisp.w0 = str2double(get(ui_w0,'String'));
        GDisp.h0 = str2double(get(ui_h0,'String'));
        
        % Display colors
        GDisp.colors = ui_S.Data(:,1);
        GDisp.colors_info = ui_S.Data(:,2);
        GDisp.dotstyle = ui_S.Data(:,3);
        GDisp.dotstyle_info = ui_S.Data(:,4);
        GDisp.linestyle = ui_S.Data(:,5);
        GDisp.linestyle_info = ui_S.Data(:,6);
        
        % Video Speed Max Channels Pixel Dynamics Box Dynamics Update
        GTraces.videospeed = str2double(get(vid,'String'));
        GTraces.NChan_max = str2double(get(chanmax,'String'));
        GTraces.NReg_max = str2double(get(regmax,'String'));
        GTraces.NPix_max = str2double(get(pixmax,'String'));
        GTraces.FrameRate = str2double(get(framerate,'String'));
        GTraces.CompressionFormat_index = compformat.Value;
        GTraces.CompressionFormat = strtrim(compformat.String(compformat.Value,:));
        GTraces.ImageSaveFormat_index = imformat.Value;
        GTraces.ImageSaveFormat = char(imextension.UserData.format(imformat.Value));
        GTraces.ImageSaveExtension = char(imextension.UserData.extension(imformat.Value));
        % Flag if gload changed
        if ~strcmp(char(gload_extension.UserData.format(gload_format.Value)),GTraces.GraphicLoadFormat)
            flag_gload = true;
        else
            flag_gload = false;
        end
        GTraces.GraphicLoadFormat_index = gload_format.Value;
        GTraces.GraphicLoadFormat = char(gload_extension.UserData.format(gload_format.Value));
        GTraces.GraphicSaveFormat_index = gsave_format.Value;
        GTraces.GraphicSaveFormat = char(gsave_extension.UserData.format(gsave_format.Value));
        GTraces.GaussianSmoothing = str2double(get(smoothing,'String'));
        
        GImport.resamp_burst = str2double(get(resamp_burst,'String'));
        GImport.resamp_cont = str2double(get(resamp_cont,'String'));
        GImport.burst_thresh = str2double(get(burst_thresh,'String'));    
        GImport.jump_thresh = str2double(get(jump_thresh,'String'));
        GImport.Doppler_normalization_index = norm_format.Value;
        GImport.Doppler_normalization = char(norm_extension.UserData.format(norm_format.Value));
        % Flag if Doppler loading changed
        if ~strcmp(char(dload_extension.UserData.format(dload_format.Value)),GImport.Doppler_loading)
            flag_dload = true;
        else
            flag_dload = false;
        end
        GImport.Doppler_loading = char(dload_extension.UserData.format(dload_format.Value));
        GImport.Doppler_loading_index=dload_format.Value;
        % Flag if Video loading changed
        if ~strcmp(char(vload_extension.UserData.format(vload_format.Value)),GImport.Video_loading)
            flag_vload = true;
        else
            flag_vload = false;
        end
        GImport.Video_loading = char(vload_extension.UserData.format(vload_format.Value));
        GImport.Video_loading_index=vload_format.Value;
        GImport.LFP_loading = char(lload_extension.UserData.format(lload_format.Value));
        GImport.LFP_loading_index=lload_format.Value;
        GImport.Channel_loading = char(cload_extension.UserData.format(cload_format.Value));
        GImport.Channel_loading_index=cload_format.Value;
        GImport.Trigger_loading = char(tload_extension.UserData.format(tload_format.Value));
        GImport.Trigger_loading_index=tload_format.Value;
        GImport.Region_loading = char(rload_extension.UserData.format(rload_format.Value));
        GImport.Region_loading_index=rload_format.Value;
        GImport.pixel_thresh = str2double(get(pixel_thresh,'String'));
        GImport.pattern_unnamed = get(pattern_unnamed,'String');
        GImport.f_def = str2double(get(f_def,'String'));
        
        GParams.SEED = SEED;
        GParams.SEED_SWL = SEED_SWL;
        GParams.sep_swl_1 = get(ui_sep_swl_1,'String');
        GParams.sep_swl_2 = get(ui_sep_swl_2,'String');
        GParams.DIR_SAVE = DIR_SAVE;
        GParams.DIR_FIG = DIR_FIG;
        GParams.DIR_STATS = DIR_STATS;
        GParams.DIR_SYNT = DIR_SYNT;
        
        GFilt.broad_inf = str2double(get(ui_broad_inf,'String'));
        GFilt.broad_sup = str2double(get(ui_broad_sup,'String'));
        GFilt.broad_smooth = str2double(get(ui_broad_smooth,'String'));
        GFilt.temp_inf = str2double(get(ui_temp_inf,'String'));
        GFilt.temp_sup = str2double(get(ui_temp_sup,'String'));
        GFilt.temp_smooth = str2double(get(ui_temp_smooth,'String'));
        GFilt.acc_inf = str2double(get(ui_acc_inf,'String'));
        GFilt.acc_sup = str2double(get(ui_acc_sup,'String'));
        GFilt.acc_smooth = str2double(get(ui_acc_smooth,'String'));
        GFilt.gyr_inf = str2double(get(ui_gyr_inf,'String'));
        GFilt.gyr_sup = str2double(get(ui_gyr_sup,'String'));
        GFilt.gyr_smooth = str2double(get(ui_gyr_smooth,'String'));
        GFilt.emg_inf = str2double(get(ui_emg_inf,'String'));
        GFilt.emg_sup = str2double(get(ui_emg_sup,'String'));
        GFilt.emg_smooth = str2double(get(ui_emg_smooth,'String'));
        
        GFilt.delta_inf = str2double(get(ui_delta_inf,'String'));
        GFilt.delta_sup = str2double(get(ui_delta_sup,'String'));
        GFilt.delta_smooth = str2double(get(ui_delta_smooth,'String'));
        GFilt.theta_inf = str2double(get(ui_theta_inf,'String'));
        GFilt.theta_sup = str2double(get(ui_theta_sup,'String'));
        GFilt.theta_smooth = str2double(get(ui_theta_smooth,'String'));
        GFilt.gammalow_inf = str2double(get(ui_gammalow_inf,'String'));
        GFilt.gammalow_sup = str2double(get(ui_gammalow_sup,'String'));
        GFilt.gammalow_smooth = str2double(get(ui_gammalow_smooth,'String'));
        GFilt.gammamid_inf = str2double(get(ui_gammamid_inf,'String'));
        GFilt.gammamid_sup = str2double(get(ui_gammamid_sup,'String'));
        GFilt.gammamid_smooth = str2double(get(ui_gammamid_smooth,'String'));
        GFilt.gammamidup_inf = str2double(get(ui_gammamidup_inf,'String'));
        GFilt.gammamidup_sup = str2double(get(ui_gammamidup_sup,'String'));
        GFilt.gammamidup_smooth = str2double(get(ui_gammamidup_smooth,'String'));
        GFilt.gammahigh_inf = str2double(get(ui_gammahigh_inf,'String'));
        GFilt.gammahigh_sup = str2double(get(ui_gammahigh_sup,'String'));
        GFilt.gammahigh_smooth = str2double(get(ui_gammahigh_smooth,'String'));
        GFilt.gammahighup_inf = str2double(get(ui_gammahighup_inf,'String'));
        GFilt.gammahighup_sup = str2double(get(ui_gammahighup_sup,'String'));
        GFilt.gammahighup_smooth = str2double(get(ui_gammahighup_smooth,'String'));
        GFilt.ripple_inf = str2double(get(ui_ripple_inf,'String'));
        GFilt.ripple_sup = str2double(get(ui_ripple_sup,'String'));
        GFilt.ripple_smooth = str2double(get(ui_ripple_smooth,'String'));
        
        GColors.patch_color = get(patch_color,'BackgroundColor');
        GColors.patch_width = str2double(get(patch_width,'String'));
        GColors.patch_transparency = str2double(get(patch_transparency,'String'));
        GColors.mask_color = get(mask_color,'BackgroundColor');
        GColors.mask_width = str2double(get(mask_width,'String'));
        GColors.mask_transparency = str2double(get(mask_transparency,'String'));
        GColors.atlas_color = get(atlas_color,'BackgroundColor');
        GColors.atlas_width = str2double(get(atlas_width,'String'));
        GColors.atlas_transparency = str2double(get(atlas_transparency,'String'));
        
        for i =1:size(all_tg_colors,1)
            GColors.TimeGroups(i).Color = get(all_tg_colors(i),'BackgroundColor');
            GColors.TimeGroups(i).String = get(all_tg_string(i),'String');
            GColors.TimeGroups(i).Transparency = str2double(get(all_tg_transp(i),'String'));
            GColors.TimeGroups(i).Checked = get(all_tg_checked(i),'Value');
            GColors.TimeGroups(i).Visible = get(all_tg_visible(i),'Value');
        end
        
        selected_tab = tabgp.SelectedTab.Title;
        
        save('Preferences.mat','GParams','GDisp','GFilt','GTraces','GImport','GColors','selected_tab','-append');
        fprintf('Preferences.mat Saved %s.\n',fullfile(pwd,'Preferences.mat'));
        close(f2);
        
        % Updating Time Patches and Atlas
        boxTimePatch_Callback(handles.TimePatchBox,[],handles.RightAxes);
        boxAtlas_Callback(handles.AtlasBox,[],handles.CenterAxes);
        
        % Loading graphic data or Doppler if changed 
        global FILES CUR_FILE; 
        if flag_gload
            load_graphicdata(fullfile(DIR_SAVE,FILES(CUR_FILE).nlab),handles);
        end
        if flag_dload
            % load_global_image(fullfile(DIR_SAVE,FILES(CUR_FILE).nlab),handles.CenterPanelPopup.Value);
            load_global_image(FILES(CUR_FILE),handles.CenterPanelPopup.String(handles.CenterPanelPopup.Value,:));
            actualize_plot(handles);
        end
    end

    function resetparamButton_callback(~,~)
        tab = tabgp.SelectedTab;
        for i =1:length(tab.Children)
            if ~isempty(tab.Children(i).UserData) && isuicontrol(tab.Children(i))
                switch tab.Children(i).Style
                    case 'edit'
                        tab.Children(i).String = tab.Children(i).UserData;
                    case 'popupmenu'
                        tab.Children(i).Value = tab.Children(i).UserData;
                    case 'pushbutton'
                        tab.Children(i).BackgroundColor = tab.Children(i).UserData;
                    case 'checkbox'
                        tab.Children(i).Value = tab.Children(i).UserData;
                end
            end
        end
        if strcmp(tab.Title,'Display') && ~isempty(ui_S.UserData)
            a = ui_S.UserData(ui_S.UserData(:,2)==1);
            b = ui_S.UserData(ui_S.UserData(:,2)==2);
            ui_S.Data(a,1) = GDisp.colors(a);
            ui_S.Data(a,2) = GDisp.colors_info(b,:);
        end
    end

    function resetAllparamButton_callback(~,~)
        alltabs = tabgp.Children;
        for tab=1:length(alltabs)
            for i =1:length(alltabs(tab).Children)
                if ~isempty(alltabs(tab).Children(i).UserData) && isuicontrol(alltabs(tab).Children(i))
                    %set(alltabs(tab).Children(i),'String',alltabs(tab).Children(i).UserData);
                    switch alltabs(tab).Children(i).Style
                        case 'edit'
                            alltabs(tab).Children(i).String = alltabs(tab).Children(i).UserData;
                        case 'popupmenu'
                            alltabs(tab).Children(i).Value = alltabs(tab).Children(i).UserData;
                    end
                end
            end
        end
        set(ui_S,'Data',[GDisp_default.colors,GDisp_default.colors_info,GDisp_default.dotstyle,...
            GDisp_default.dotstyle_info,GDisp_default.linestyle,GDisp_default.linestyle_info]);
    end

    function checkdir_callback(hObj,~,var,label)
        StrValue=get(hObj,'String');
        if isdir(StrValue) && strcmp(StrValue,var)==0
            if ~strcmp(StrValue(end),filesep)
                StrValue = strcat(StrValue,filesep);
                set(hObj,'String',StrValue);
            end
        elseif isdir(StrValue)==0
            errordlg(sprintf('%s must be a directory.',label),'Directory Not found','modal');
            set(hObj,'String',var);
            return;
        end
    end

    function checkinteger_callback(hObj,~,var,label,inf,sup)
        vs = round(str2double(get(hObj,'String')));
        if (vs>=inf && vs<=sup)
            set(hObj,'String',vs);
        else
            errordlg(sprintf('%s must be between %d and %d',label,inf,sup),'modal');
            set(hObj,'String',var);
            return;
        end
    end

    function checkfloat_callback(hObj,~,var,label,inf,sup)
        vs = str2double(get(hObj,'String'));
        if (vs>=inf && vs<=sup)
            set(hObj,'String',vs);
        else
            errordlg(sprintf('%s must be between %.2f and %.2f',label,inf,sup),'modal');
            set(hObj,'String',var);
            return;
        end
    end

    function pickcolor_callback(hObj,~)
        hObj.BackgroundColor = uisetcolor(hObj.BackgroundColor);
    end

%%%%%%%%%%%%%%%%%%%%%%%%% Tab General Commands %%%%%%%%%%%%%%%%%%%%%%%%%

% SEED directory - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-6.5 20 2],...
    'String','Data Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_seed = uicontrol('Style','edit',...
    'Units','characters',...
    'String',SEED,...
    'Position',[22 pos(4)-6 W-24 2],...
    'Callback',{@checkdir_callback,SEED,'SEED'},...
    'TooltipString','SEED',...
    'UserData',GParams_default.SEED,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);

% SEED_SWL - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-10.5 20 2],...
    'String','NReclists Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_seed_swl = uicontrol('Style','edit',...
    'Units','characters',...
    'String',SEED_SWL,...
    'TooltipString','SEED_SWL',...
    'UserData',GParams_default.SEED_SWL,...
    'Position',[22 pos(4)-10 W-24 2],...
    'Callback',{@checkdir_callback,SEED_SWL,'SEED_SWL'},...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% sep_swl - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-12.5 20 2],...
    'String','SWL Separators',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_sep_swl_1 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GParams.sep_swl_1,...
    'Position',[22 pos(4)-12 (W-24)/2 2],...
    'TooltipString','sep_swl_1',...
    'UserData',GParams_default.sep_swl_1,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_sep_swl_2 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GParams.sep_swl_2,...
    'TooltipString','sep_swl_2',...
    'UserData',GParams_default.sep_swl_2,...
    'Position',[22+(W-24)/2 pos(4)-12 (W-24)/2 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% SEED_REGION - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-14.5 20 2],...
    'String','NRegions Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_seed_region = uicontrol('Style','edit',...
    'Units','characters',...
    'String',SEED_REGION,...
    'TooltipString','SEED_REGION',...
    'UserData',GParams_default.SEED_REGION,...
    'Position',[22 pos(4)-14 W-24 2],...
    'Callback',{@checkdir_callback,SEED_REGION,'SEED_REGION'},...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% SEED_CONFIG - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-16.5 20 2],...
    'String','NConfigs Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_seed_config = uicontrol('Style','edit',...
    'Units','characters',...
    'String',SEED_CONFIG,...
    'TooltipString','SEED_CONFIG',...
    'UserData',GParams_default.SEED_CONFIG,...
    'Position',[22 pos(4)-16 W-24 2],...
    'Callback',{@checkdir_callback,SEED_CONFIG,'SEED_CONFIG'},...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% SEED_ATLAS - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-18.5 20 2],...
    'String','NAtlas Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_seed_atlas = uicontrol('Style','edit',...
    'Units','characters',...
    'String',SEED_ATLAS,...
    'TooltipString','SEED_ATLAS',...
    'UserData',GParams_default.SEED_ATLAS,...
    'Position',[22 pos(4)-18 W-24 2],...
    'Callback',{@checkdir_callback,SEED_ATLAS,'SEED_ATLAS'},...
    'BackgroundColor',panelColor,...
    'Parent',tab0);

% SAVE directory - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-22.5 20 2],...
    'String','Saving Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_dir_save = uicontrol('Style','edit',...
    'Units','characters',...
    'String',DIR_SAVE,...
    'Position',[22 pos(4)-22 W-24 2],...
    'Callback',{@checkdir_callback,DIR_SAVE,'DIR_SAVE'},...
    'TooltipString','DIR_SAVE',...
    'UserData',GParams_default.DIR_SAVE,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% FIGURE directory - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-24.5 20 2],...
    'String','Figure Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_dir_fig = uicontrol('Style','edit',...
    'Units','characters',...
    'String',DIR_FIG,...
    'Position',[22 pos(4)-24 W-24 2],...
    'Callback',{@checkdir_callback,DIR_FIG,'DIR_FIG'},...
    'TooltipString','DIR_FIG',...
    'UserData',GParams_default.DIR_FIG,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% STATISTICS directory - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-26.5 20 2],...
    'String','Statistics Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_dir_stats = uicontrol('Style','edit',...
    'Units','characters',...
    'String',DIR_STATS,...
    'Position',[22 pos(4)-26 W-24 2],...
    'Callback',{@checkdir_callback,DIR_STATS,'DIR_STATS'},...
    'TooltipString','DIR_STATS',...
    'UserData',GParams_default.DIR_STATS,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% SYNTHESIS directory - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-28.5 20 2],...
    'String','Synthesis Directory',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
ui_dir_synt = uicontrol('Style','edit',...
    'Units','characters',...
    'String',DIR_SYNT,...
    'Position',[22 pos(4)-28 W-24 2],...
    'Callback',{@checkdir_callback,DIR_SYNT,'DIR_SYNT'},...
    'TooltipString','DIR_SYNT',...
    'UserData',GParams_default.DIR_SYNT,...
    'BackgroundColor',panelColor,...
    'Parent',tab0);

%%%%%%%%%%%%%%%%%%%%%%%%% Tab Display Commands %%%%%%%%%%%%%%%%%%%%%%%%%
% W Label
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-6.5 20 2],...
    'String','Initial Window Width',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab4);
ui_W = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GDisp.W,...
    'Position',[22 pos(4)-6 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','W',...
    'UserData',GDisp_default.W,...
    'Parent',tab4);

% H Label
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[W/2 pos(4)-6.5 20 2],...
    'String','Initial Window Height',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab4);
ui_H = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GDisp.H,...
    'Position',[W/2+22 pos(4)-6 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','H',...
    'UserData',GDisp_default.H,...
    'Parent',tab4);

% w0 Label
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-8.5 20 2],...
    'String','Center Panel Width',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab4);
ui_w0 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GDisp.w0,...
    'Position',[22 pos(4)-8 10 2],...
    'TooltipString','w0',...
    'UserData',GDisp_default.w0,...
    'BackgroundColor',panelColor,...
    'Parent',tab4);

% h0 Label
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[W/2 pos(4)-8.5 20 2],...
    'String','Center Panel Height',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab4);
ui_h0 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GDisp.h0,...
    'Position',[W/2+22 pos(4)-8 10 2],...
    'TooltipString','h0',...
    'UserData',GDisp_default.h0,...
    'BackgroundColor',panelColor,...
    'Parent',tab4);

set(ui_W,'Callback',{@checkfloat_callback,GDisp.W,'Window Width',0,1});
set(ui_H,'Callback',{@checkfloat_callback,GDisp.H,'Window Height',0,1});
set(ui_w0,'Callback',{@checkfloat_callback,GDisp.w0,'Image Width',.30,.50});
set(ui_h0,'Callback',{@checkfloat_callback,GDisp.h0,'Image Height',.10,.30});

% Table of styles
ui_S = uitable('ColumnName',{'color','info','dotstyle','info','linestyle','info'},...
    'ColumnFormat',{'char','char','char','char','char','char'},...
    'ColumnEditable',[true,true,false,false,false,false],...
    'ColumnWidth',{100 100 80 100 80 80},...
    'Data',[GDisp.colors,GDisp.colors_info,GDisp.dotstyle,GDisp.dotstyle_info,GDisp.linestyle,GDisp.linestyle_info],...
    'Tag','Style_uitable = ',...
    'Units','characters',...
    'CellEditCallback',@style_uitable_edit,...
    'CellSelectionCallback',@(src,evnt)set(src,'UserData',evnt.Indices),...
    'Position',[0 0 W H-14],...
    'Parent',tab4);

    function style_uitable_edit(hObj,evnt)
        
        r = evnt.Indices(1);
        c = evnt.Indices(2);
        switch c
            case 1
                hObj.Data{r,c} = mat2str(char2rgb(evnt.EditData),2);
                if ismember(rgb2char(char2rgb(evnt.EditData)),GDisp.colors_info)
                    [~,b] = ismember(rgb2char(char2rgb(evnt.EditData)),GDisp.colors_info);
                    hObj.Data{r,2} = char(GDisp.colors_info(b));
                else
                    hObj.Data{r,2} = sprintf('color_%d',r);
                end
                if hObj.Data{r,c}==''''
                    hObj.Data{r,c}='';
                end
            case 2
                if isempty(hObj.Data{r,1})
                    hObj.Data{r,1}=mat2str(char2rgb('rand'),2);
                end
        end
    end


%%%%%%%%%%%%%%%%%%%%%%% Tab Traces Commands %%%%%%%%%%%%%%%%%%%%%%%%%
% VIDEO SPEED -  Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-6.5 30 2],...
    'String','Video Speed',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
vid = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.videospeed,...
    'Position',[32 pos(4)-6 10 2],...
    'TooltipString','frames per second',...
    'UserData',GTraces_default.videospeed,...
    'Callback',{@checkfloat_callback,GTraces.videospeed,'Video Speed',.5,1000},...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% MAX CHANNELS -  Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-8.5 30 2],...
    'HorizontalAlignment','left',...
    'String','# Max Channels Shown',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
chanmax = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.NChan_max,...
    'Position',[32 pos(4)-8 10 2],...
    'TooltipString','Maximum Channels Display',...
    'UserData',GTraces_default.NChan_max,...
    'Callback',{@checkinteger_callback,GTraces.NChan_max,'Max Channels',1,GTraces_default.NChan_max},...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% PIXEL DYNAMICS - Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-10.5 30 2],...
    'HorizontalAlignment','left',...
    'String','# Max Pixels Shown',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
pixmax = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.NPix_max,...
    'Position',[32 pos(4)-10 10 2],...
    'TooltipString','Maximum Pixels Display',...
    'UserData',GTraces_default.NPix_max,...
    'Callback',{@checkinteger_callback,GTraces.NPix_max,'Max Pixels',1,GTraces.NChan_max},...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% BOX DYNAMICS -  Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-12.5 30 2],...
    'HorizontalAlignment','left',...
    'String','# Max Boxes Shown',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
regmax = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.NReg_max,...
    'TooltipString','Maximum Boxes Display',...
    'UserData',GTraces_default.NReg_max,...
    'Callback',{@checkinteger_callback,GTraces.NReg_max,'Max Boxes',1,GTraces.NChan_max},...
    'Position',[32 pos(4)-12 10 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% Saving Frame Rate -  Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-14.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Saving Frame Rate',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
framerate = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.FrameRate,...
    'TooltipString','Video Save Frame Rate',...
    'UserData',GTraces_default.FrameRate,...
    'Callback',{@checkinteger_callback,GTraces.FrameRate,'Frame Rate',1,50},...
    'Position',[32 pos(4)-14 10 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

%Compression Format -  Popup Menu
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-16.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Compression Format',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('(1) MPEG-4 file / H.264 encoding \n(2) AVI file / Motion JPEG encoding\n(3) Motion JPEG 2000\n(4) Motion JPEG 2000 file with lossless compression\n(5) Uncompressed AVI file with RGB24 video\n(6) Uncompressed AVI file with indexed video\n(7) Uncompressed AVI file with grayscale video'),...
    'Parent',tab2);
compformat = uicontrol('Style','popup',...
    'Units','characters',...
    'String','MPEG-4|Motion JPEG AVI|Motion JPEG 2000|Archival|Uncompressed AVI|Indexed AVI|Grayscale AVI',...
    'Value',GTraces.CompressionFormat_index,...
    'UserData',1,...
    'Position',[32 pos(4)-16.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

str='JPEG 24-bit|PNG 24-bit|Full page Portable Document Format (PDF) color|MATLAB FIG file';
str=strcat(str,'|','TIFF 24-bit (compressed)|TIFF 24-bit (not compressed)|SVG (scalable vector graphics)|BMP 24-bit');
str=strcat(str,'|','BMP 8-bit (256 color, uses a fixed colormap)|HDF 24-bit|PBM (plain format) 1-bit|PCX 24-bit color (three 8-bit planes)');
str=strcat(str,'|','PGM (plain format)|PPM (plain format)|Encapsulated PostScript (EPS) Level 3 black and white|Encapsulated PostScript (EPS) Level 3 color');
str=strcat(str,'|','Full-page PostScript (PS) Level 3 black and white|Full-page PostScript (PS) Level 3 color|Enhanced Metafile (Windows only)	.emf');

% Image Save Format -  Popup Menu
imextension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-18.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Image Saving Format',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Default Extensions\n.jpg\n.png\n.pdf\n.fig\n.tif\n.tif\n.svg\n.bmp\n.bmp\n.hdf\n.pbm\n.pcx\n.pgm\n.ppm\n.eps\n.eps\n.ps\n.ps\n.emf'),...
    'Parent',tab2);
imextension.UserData.format={'jpeg';'png';'pdf';'fig';'tiff';'tiffn';'svg';'bmp';'bmp256';'hdf';'pbm';'pcx24b';'pgm';'ppm';'eps';'epsc';'ps';'psc';'meta'};
imextension.UserData.extension={'.jpg';'.png';'.pdf';'.fig';'.tif';'.tif';'.svg';'.bmp';'.bmp';'.hdf';'.pbm';'pcx';'.pgm';'.ppm';'.eps';'.eps';'.ps';'.ps';'.emf'};
imformat = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GTraces.ImageSaveFormat_index,...
    'UserData',1,...
    'Position',[32 pos(4)-18.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% Graphic Load Format -  Popup Menu
str='Light Files|Full Files (LFP/MUA)';
gload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-20.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Graphic Object Load Format',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('File name when loading graphic objects'),...
    'Parent',tab2);
gload_extension.UserData.format={'Graphic_objects.mat';'Graphic_objects_full.mat'};
gload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GTraces.GraphicLoadFormat_index,...
    'TooltipString','Graphic_objects.mat|Graphic_objects_full.mat',...
    'UserData',1,...
    'Position',[32 pos(4)-20.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
% Graphic Save Format -  Popup Menu
str='Light Files|Full Files (LFP/MUA)|skip';
gsave_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-22.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Graphic Object Save Format',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('File name when saving graphic objects'),...
    'Parent',tab2);
gsave_extension.UserData.format={'Graphic_objects.mat';'Graphic_objects_full.mat';'skip'};
gsave_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GTraces.GraphicSaveFormat_index,...
    'TooltipString','Graphic_objects.mat|Graphic_objects_full.mat|skip',...
    'UserData',1,...
    'Position',[32 pos(4)-22.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

% Smoothing time constant -  Editable text
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-24.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Gaussian Smoothing',...
    'BackgroundColor',panelColor,...
    'Parent',tab2);
smoothing = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GTraces.GaussianSmoothing,...
    'TooltipString','Trace Smoothing (s)',...
    'UserData',GTraces_default.GaussianSmoothing,...
    'Callback',{@checkfloat_callback,GTraces.GaussianSmoothing,'Gaussian Smoothing',0,60},...
    'Position',[32 pos(4)-24 10 1.5],...
    'BackgroundColor',panelColor,...
    'Parent',tab2);

%%%%%%%%%%%%%%%%%%%%%%% Tab Traces Commands %%%%%%%%%%%%%%%%%%%%%%%%%
% Burst threshold
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-6.5 30 2],...
    'String','Burst Detection',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
burst_thresh = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.burst_thresh,...
    'Position',[32 pos(4)-6 10 2],...
    'TooltipString','Threshold for burst detection (s)',...
    'UserData',GImport_default.burst_thresh,...
    'Callback',{@checkfloat_callback,GImport.burst_thresh,'Burst Threshold Detection',5,60},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Jump threshold
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-8.5 30 2],...
    'String','Jump Detection',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
jump_thresh = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.jump_thresh,...
    'Position',[32 pos(4)-8 10 2],...
    'TooltipString','Threshold for jump detection (s)',...
    'UserData',GImport_default.jump_thresh,...
    'Callback',{@checkfloat_callback,GImport.jump_thresh,'Burst Threshold Detection',0,60},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Resampling Rate Burst
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-10.5 30 2],...
    'String','Burst Resampling Rate',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
resamp_burst = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.resamp_burst,...
    'Position',[32 pos(4)-10 10 2],...
    'TooltipString','Resampling Rate Burst',...
    'UserData',GImport_default.resamp_burst,...
    'Callback',{@checkfloat_callback,GImport.resamp_burst,'Burst Resampling Rate',.1,10},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Resampling Rate Continuous
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-12.5 30 2],...
    'String','Continuous Resampling Rate',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
resamp_cont = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.resamp_cont,...
    'Position',[32 pos(4)-12 10 2],...
    'TooltipString','Resampling Rate Cont',...
    'UserData',GImport_default.resamp_cont,...
    'Callback',{@checkfloat_callback,GImport.resamp_cont,'Burst Resampling Rate',.1,10},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Doppler Normalization
str='DeltaMean/std|DeltaMean/mean|DeltaMean/baseline';
norm_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-14.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Doppler Normalization',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Normalization type Doppler_normalized'),...
    'Parent',tab1);
norm_extension.UserData.format={'std';'mean';'baseline';};
norm_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Doppler_normalization_index,...
    'TooltipString','std|mean|baseline',...
    'UserData',1,...
    'Position',[32 pos(4)-14.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Doppler loading
str='full|skip';
dload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-16.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Doppler Loading',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Doppler loading mode'),...
    'Parent',tab1);
dload_extension.UserData.format={'full';'skip';};
dload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Doppler_loading_index,...
    'TooltipString','full|skip',...
    'UserData',1,...
    'Position',[32 pos(4)-16.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Video loading
str='full|skip';
vload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-18.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Video Loading',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Video loading mode'),...
    'Parent',tab1);
vload_extension.UserData.format={'full';'skip';};
vload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Video_loading_index,...
    'TooltipString','full|skip',...
    'UserData',1,...
    'Position',[32 pos(4)-18.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% LFP loading
str='ns1|ns2|ns3|ns4|ns5|ns6|all';
lload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-20.5 30 2],...
    'HorizontalAlignment','left',...
    'String','LFP Importation',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('LFP Importation mode'),...
    'Parent',tab1);
lload_extension.UserData.format={'ns1';'ns2';'ns3';'ns4';'ns5';'ns6';'all'};
lload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.LFP_loading_index,...
    'TooltipString','ns1|ns2|ns3|ns4|ns5|ns6|all',...
    'UserData',2,...
    'Position',[32 pos(4)-20.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% LFP Channel loading
str='source|differential|all';
cload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-22.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Channel Type',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('LFP channel importation'),...
    'Parent',tab1);
cload_extension.UserData.format={'source';'differential';'all'};
cload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Channel_loading_index,...
    'TooltipString','source|differential|all',...
    'UserData',1,...
    'Position',[32 pos(4)-22.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Trigger loading
str='ns5|nev';
tload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-24.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Trigger Importation',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Trigger preferential importation'),...
    'Parent',tab1);
tload_extension.UserData.format={'ns5';'nev'};
tload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Trigger_loading_index,...
    'TooltipString','ns5|nev',...
    'UserData',1,...
    'Position',[32 pos(4)-24.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Region loading
str='unilateral|bilateral|all';
rload_extension = uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-26.5 30 2],...
    'HorizontalAlignment','left',...
    'String','Region Importation',...
    'BackgroundColor',panelColor,...
    'TooltipString',sprintf('Region preferential importation'),...
    'Parent',tab1);
rload_extension.UserData.format={'unilateral';'bilateral';'all'};
rload_format = uicontrol('Style','popup',...
    'Units','characters',...
    'String',str,...
    'Value',GImport.Region_loading_index,...
    'TooltipString','unilateral|bilateral|all',...
    'UserData',1,...
    'Position',[32 pos(4)-26.5 30 2],...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Neuroshop Pixel threshold
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-28.5 30 2],...
    'TooltipString','Minimum Region Size',...
    'String','Neuroshop Pixel threshold',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
pixel_thresh = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.pixel_thresh,...
    'Position',[32 pos(4)-28 10 1.75],...
    'TooltipString','100 (default)',...
    'UserData',GImport_default.pixel_thresh,...
    'Callback',{@checkfloat_callback,GImport.pixel_thresh,'Neuroshop Pixel threshold',0,10000},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Neuroshop Unnamed Pattern
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-30.5 30 2],...
    'TooltipString','Automatically discarding regions containing this pattern',...
    'String','Region Exclusion Pattern',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
pattern_unnamed = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.pattern_unnamed,...
    'Position',[32 pos(4)-30 20 1.75],...
    'TooltipString','region (default)',...
    'UserData',GImport_default.pattern_unnamed,...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

% Default Sampling Rate
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-32.5 30 2],...
    'TooltipString','fUS default rate (Hz)',...
    'String','Default Sampling Rate',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab1);
f_def = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GImport.f_def,...
    'Position',[32 pos(4)-32 10 1.75],...
    'TooltipString','2.5 Hz (continuous mode)',...
    'UserData',GImport_default.f_def,...
    'Callback',{@checkfloat_callback,GImport.f_def,'Default Sampling Rate',0,10000},...
    'BackgroundColor',panelColor,...
    'Parent',tab1);

%%%%%%%%%%%%%%%%%%%%%%% Tab Filtering Commands %%%%%%%%%%%%%%%%%%%%%%%%%
% Broad
delta = [6,8,10,12,14,18,20,22,24,26,28,30,32];
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(1)-.5 30 2],...
    'String','LFP Broad band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_broad_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.broad_inf,...
    'Position',[32 pos(4)-delta(1) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.broad_inf,...
    'Parent',tab3);
ui_broad_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.broad_sup,...
    'Position',[42 pos(4)-delta(1) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.broad_sup,...
    'Parent',tab3);
ui_broad_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.broad_smooth,...
    'Position',[52 pos(4)-delta(1) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.broad_smooth,...
    'Parent',tab3);
set(ui_broad_inf,'Callback',{@checkfloat_callback,GFilt.broad_inf,'Freq inf',0,500});
set(ui_broad_sup,'Callback',{@checkfloat_callback,GFilt.broad_sup,'Freq sup',0,500});
set(ui_broad_smooth,'Callback',{@checkfloat_callback,GFilt.broad_smooth,'T smooth',0,60});

% Temp Broad
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(2)-.5 30 2],...
    'String','TEMP Broad band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_temp_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.temp_inf,...
    'Position',[32 pos(4)-delta(2) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.temp_inf,...
    'Parent',tab3);
ui_temp_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.temp_sup,...
    'Position',[42 pos(4)-delta(2) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.temp_sup,...
    'Parent',tab3);
ui_temp_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.temp_smooth,...
    'Position',[52 pos(4)-delta(2) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.temp_smooth,...
    'Parent',tab3);
set(ui_temp_inf,'Callback',{@checkfloat_callback,GFilt.temp_inf,'Freq inf',0,500});
set(ui_temp_sup,'Callback',{@checkfloat_callback,GFilt.temp_sup,'Freq sup',0,500});
set(ui_temp_smooth,'Callback',{@checkfloat_callback,GFilt.temp_smooth,'T smooth',0,60});

% Acc Broad
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(3)-.5 30 2],...
    'String','ACC Broad band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_acc_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.acc_inf,...
    'Position',[32 pos(4)-delta(3) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.acc_inf,...
    'Parent',tab3);
ui_acc_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.acc_sup,...
    'Position',[42 pos(4)-delta(3) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.acc_sup,...
    'Parent',tab3);
ui_acc_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.acc_smooth,...
    'Position',[52 pos(4)-delta(3) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.acc_smooth,...
    'Parent',tab3);
set(ui_acc_inf,'Callback',{@checkfloat_callback,GFilt.acc_inf,'Freq inf',0,500});
set(ui_acc_sup,'Callback',{@checkfloat_callback,GFilt.acc_sup,'Freq sup',0,500});
set(ui_acc_smooth,'Callback',{@checkfloat_callback,GFilt.acc_smooth,'T smooth',0,60});

% Gyr Broad
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(4)-.5 30 2],...
    'String','GYR Broad band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gyr_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gyr_inf,...
    'Position',[32 pos(4)-delta(4) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gyr_inf,...
    'Parent',tab3);
ui_gyr_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gyr_sup,...
    'Position',[42 pos(4)-delta(4) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gyr_sup,...
    'Parent',tab3);
ui_gyr_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gyr_smooth,...
    'Position',[52 pos(4)-delta(4) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gyr_smooth,...
    'Parent',tab3);
set(ui_gyr_inf,'Callback',{@checkfloat_callback,GFilt.gyr_inf,'Freq inf',0,500});
set(ui_gyr_sup,'Callback',{@checkfloat_callback,GFilt.gyr_sup,'Freq sup',0,500});
set(ui_gyr_smooth,'Callback',{@checkfloat_callback,GFilt.gyr_smooth,'T smooth',0,60});

% Emg Broad
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(5)-.5 30 2],...
    'String','EMG Broad band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_emg_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.emg_inf,...
    'Position',[32 pos(4)-delta(5) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.emg_inf,...
    'Parent',tab3);
ui_emg_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.emg_sup,...
    'Position',[42 pos(4)-delta(5) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.emg_sup,...
    'Parent',tab3);
ui_emg_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.emg_smooth,...
    'Position',[52 pos(4)-delta(5) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.emg_smooth,...
    'Parent',tab3);
set(ui_emg_inf,'Callback',{@checkfloat_callback,GFilt.emg_inf,'Freq inf',0,500});
set(ui_emg_sup,'Callback',{@checkfloat_callback,GFilt.emg_sup,'Freq sup',0,500});
set(ui_emg_smooth,'Callback',{@checkfloat_callback,GFilt.emg_smooth,'T smooth',0,60});

% Delta
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(6)-.5 30 2],...
    'String','Delta band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_delta_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.delta_inf,...
    'Position',[32 pos(4)-delta(6) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.delta_inf,...
    'Parent',tab3);
ui_delta_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.delta_sup,...
    'Position',[42 pos(4)-delta(6) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.delta_sup,...
    'Parent',tab3);
ui_delta_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.delta_smooth,...
    'Position',[52 pos(4)-delta(6) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.delta_smooth,...
    'Parent',tab3);
set(ui_delta_inf,'Callback',{@checkfloat_callback,GFilt.delta_inf,'Freq inf',0,500});
set(ui_delta_sup,'Callback',{@checkfloat_callback,GFilt.delta_sup,'Freq sup',0,500});
set(ui_delta_smooth,'Callback',{@checkfloat_callback,GFilt.delta_smooth,'T smooth',0,60});

% Theta
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(7)-.5 30 2],...
    'String','Theta band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_theta_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.theta_inf,...
    'Position',[32 pos(4)-delta(7) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.theta_inf,...
    'Parent',tab3);
ui_theta_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.theta_sup,...
    'Position',[42 pos(4)-delta(7) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.theta_sup,...
    'Parent',tab3);
ui_theta_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.theta_smooth,...
    'Position',[52 pos(4)-delta(7) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.theta_smooth,...
    'Parent',tab3);
set(ui_theta_inf,'Callback',{@checkfloat_callback,GFilt.theta_inf,'Freq inf',0,500});
set(ui_theta_sup,'Callback',{@checkfloat_callback,GFilt.theta_sup,'Freq sup',0,500});
set(ui_theta_smooth,'Callback',{@checkfloat_callback,GFilt.theta_smooth,'T smooth',0,60});

% Gammalow
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(8)-.5 30 2],...
    'String','Gammalow band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gammalow_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammalow_inf,...
    'Position',[32 pos(4)-delta(8) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gammalow_inf,...
    'Parent',tab3);
ui_gammalow_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammalow_sup,...
    'Position',[42 pos(4)-delta(8) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gammalow_sup,...
    'Parent',tab3);
ui_gammalow_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammalow_smooth,...
    'Position',[52 pos(4)-delta(8) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gammalow_smooth,...
    'Parent',tab3);
set(ui_gammalow_inf,'Callback',{@checkfloat_callback,GFilt.gammalow_inf,'Freq inf',0,500});
set(ui_gammalow_sup,'Callback',{@checkfloat_callback,GFilt.gammalow_sup,'Freq sup',0,500});
set(ui_gammalow_smooth,'Callback',{@checkfloat_callback,GFilt.gammalow_smooth,'T smooth',0,60});

% Gammamid
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(9)-.5 30 2],...
    'String','Gammamid band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gammamid_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamid_inf,...
    'Position',[32 pos(4)-delta(9) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gammamid_inf,...
    'Parent',tab3);
ui_gammamid_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamid_sup,...
    'Position',[42 pos(4)-delta(9) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gammamid_sup,...
    'Parent',tab3);
ui_gammamid_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamid_smooth,...
    'Position',[52 pos(4)-delta(9) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gammamid_smooth,...
    'Parent',tab3);
set(ui_gammamid_inf,'Callback',{@checkfloat_callback,GFilt.gammamid_inf,'Freq inf',0,500});
set(ui_gammamid_sup,'Callback',{@checkfloat_callback,GFilt.gammamid_sup,'Freq sup',0,500});
set(ui_gammamid_smooth,'Callback',{@checkfloat_callback,GFilt.gammamid_smooth,'T smooth',0,60});

% Gammamidup
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(10)-.5 30 2],...
    'String','Gammamidup band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gammamidup_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamidup_inf,...
    'Position',[32 pos(4)-delta(10) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gammamidup_inf,...
    'Parent',tab3);
ui_gammamidup_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamidup_sup,...
    'Position',[42 pos(4)-delta(10) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gammamidup_sup,...
    'Parent',tab3);
ui_gammamidup_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammamidup_smooth,...
    'Position',[52 pos(4)-delta(10) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gammamidup_smooth,...
    'Parent',tab3);
set(ui_gammamidup_inf,'Callback',{@checkfloat_callback,GFilt.gammamidup_inf,'Freq inf',0,500});
set(ui_gammamidup_sup,'Callback',{@checkfloat_callback,GFilt.gammamidup_sup,'Freq sup',0,500});
set(ui_gammamidup_smooth,'Callback',{@checkfloat_callback,GFilt.gammamidup_smooth,'T smooth',0,60});

% Gammahigh
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(11)-.5 30 2],...
    'String','Gammahigh band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gammahigh_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahigh_inf,...
    'Position',[32 pos(4)-delta(11) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gammahigh_inf,...
    'Parent',tab3);
ui_gammahigh_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahigh_sup,...
    'Position',[42 pos(4)-delta(11) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gammahigh_sup,...
    'Parent',tab3);
ui_gammahigh_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahigh_smooth,...
    'Position',[52 pos(4)-delta(11) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gammahigh_smooth,...
    'Parent',tab3);
set(ui_gammahigh_inf,'Callback',{@checkfloat_callback,GFilt.gammahigh_inf,'Freq inf',0,500});
set(ui_gammahigh_sup,'Callback',{@checkfloat_callback,GFilt.gammahigh_sup,'Freq sup',0,500});
set(ui_gammahigh_smooth,'Callback',{@checkfloat_callback,GFilt.gammahigh_smooth,'T smooth',0,60});

% Gammahigh
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(12)-.5 30 2],...
    'String','Gammahighup band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_gammahighup_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahighup_inf,...
    'Position',[32 pos(4)-delta(12) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.gammahighup_inf,...
    'Parent',tab3);
ui_gammahighup_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahighup_sup,...
    'Position',[42 pos(4)-delta(12) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.gammahighup_sup,...
    'Parent',tab3);
ui_gammahighup_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.gammahighup_smooth,...
    'Position',[52 pos(4)-delta(12) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.gammahighup_smooth,...
    'Parent',tab3);
set(ui_gammahighup_inf,'Callback',{@checkfloat_callback,GFilt.gammahighup_inf,'Freq inf',0,500});
set(ui_gammahighup_sup,'Callback',{@checkfloat_callback,GFilt.gammahighup_sup,'Freq sup',0,500});
set(ui_gammahighup_smooth,'Callback',{@checkfloat_callback,GFilt.gammahighup_smooth,'T smooth',0,60});

% Ripple
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-delta(13)-.5 30 2],...
    'String','Ripple band',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab3);
ui_ripple_inf = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.ripple_inf,...
    'Position',[32 pos(4)-delta(13) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Down Freq',...
    'UserData',GFilt_default.ripple_inf,...
    'Parent',tab3);
ui_ripple_sup = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.ripple_sup,...
    'Position',[42 pos(4)-delta(13) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Up Freq',...
    'UserData',GFilt_default.ripple_sup,...
    'Parent',tab3);
ui_ripple_smooth = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GFilt.ripple_smooth,...
    'Position',[52 pos(4)-delta(13) 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Smoothing constant (s)',...
    'UserData',GFilt_default.ripple_smooth,...
    'Parent',tab3);
set(ui_ripple_inf,'Callback',{@checkfloat_callback,GFilt.ripple_inf,'Freq inf',0,500});
set(ui_ripple_sup,'Callback',{@checkfloat_callback,GFilt.ripple_sup,'Freq sup',0,500});
set(ui_ripple_smooth,'Callback',{@checkfloat_callback,GFilt.ripple_smooth,'T smooth',0,60});

%%%%%%%%%%%%%%%%%%%%%%% Tab Colors Commands %%%%%%%%%%%%%%%%%%%%%%%%%
% Patch Color
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-6.5 30 2],...
    'String','Patch Display',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab5);
patch_color = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[32 pos(4)-6 10 2],...
    'TooltipString','Edge Color',...
    'UserData',GColors_default.patch_color,...
    'BackgroundColor',GColors.patch_color,...
    'Parent',tab5);
patch_width = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.patch_width,...
    'Position',[42 pos(4)-6 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Edge width',...
    'UserData',GColors_default.patch_width,...
    'Parent',tab5);
patch_transparency = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.patch_transparency,...
    'Position',[52 pos(4)-6 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Patch transparency',...
    'UserData',GColors_default.patch_transparency,...
    'Parent',tab5);
set(patch_color,'Callback',{@pickcolor_callback});
set(patch_width,'Callback',{@checkfloat_callback,GColors.patch_width,'Width',0.1,5});
set(patch_transparency,'Callback',{@checkfloat_callback,GColors.patch_transparency,'Transparency',0,1});

% Mask Color
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-8.5 30 2],...
    'String','Mask Display',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab5);
mask_color = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[32 pos(4)-8 10 2],...
    'TooltipString','Edge Color',...
    'UserData',GColors_default.mask_color,...
    'BackgroundColor',GColors.mask_color,...
    'Parent',tab5);
mask_width = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.mask_width,...
    'Position',[42 pos(4)-8 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Edge width',...
    'UserData',GColors_default.mask_width,...
    'Parent',tab5);
mask_transparency = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.mask_transparency,...
    'Position',[52 pos(4)-8 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Patch transparency',...
    'UserData',GColors_default.mask_transparency,...
    'Parent',tab5);
set(mask_color,'Callback',{@pickcolor_callback});
set(mask_width,'Callback',{@checkfloat_callback,GColors.mask_width,'Width',0.1,5});
set(mask_transparency,'Callback',{@checkfloat_callback,GColors.mask_transparency,'Transparency',0,1});

% Atlas Color
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-10.5 30 2],...
    'String','Atlas Display',...
    'HorizontalAlignment','left',...
    'BackgroundColor',panelColor,...
    'Parent',tab5);
atlas_color = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[32 pos(4)-10 10 2],...
    'TooltipString','Color',...
    'UserData',GColors_default.atlas_color,...
    'BackgroundColor',GColors.atlas_color,...
    'Parent',tab5);
atlas_width = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.atlas_width,...
    'Position',[42 pos(4)-10 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','Linewidth',...
    'UserData',GColors_default.atlas_width,...
    'Parent',tab5);
atlas_transparency = uicontrol('Style','edit',...
    'Units','characters',...
    'String',GColors.atlas_transparency,...
    'Position',[52 pos(4)-10 10 2],...
    'BackgroundColor',panelColor,...
    'TooltipString','transparency',...
    'UserData',GColors_default.atlas_transparency,...
    'Parent',tab5);
set(atlas_color,'Callback',{@pickcolor_callback});
set(atlas_width,'Callback',{@checkfloat_callback,GColors.atlas_width,'Width',0.1,5});
set(atlas_transparency,'Callback',{@checkfloat_callback,GColors.atlas_transparency,'Transparency',0,1});

% Atlas Color
all_offsets = [14;16;18;20;22;24];
all_tg_colors = [];
all_tg_string = [];
all_tg_transp = [];
all_tg_checked = [];
all_tg_visible = [];
for index = 1:size(all_offsets,1)
    offset = all_offsets(index);
    uicontrol('Style','text',...
        'Units','characters',...
        'Position',[2 pos(4)-offset-.5 30 2],...
        'String',sprintf('[TimeGroup] %s',GColors.TimeGroups(index).Name),...
        'HorizontalAlignment','left',...
        'BackgroundColor',panelColor,...
        'Parent',tab5);
    tg_color = uicontrol('Style','pushbutton',...
        'Units','characters',...
        'Position',[32 pos(4)-offset 10 2],...
        'TooltipString','Color',...
        'UserData',GColors_default.TimeGroups(index).Color,...
        'BackgroundColor',GColors.TimeGroups(index).Color,...
        'Parent',tab5);
    tg_transp = uicontrol('Style','edit',...
        'Units','characters',...
        'String',GColors.TimeGroups(index).Transparency,...
        'Position',[42 pos(4)-offset 10 2],...
        'BackgroundColor',panelColor,...
        'TooltipString','transparency',...
        'UserData',GColors_default.TimeGroups(index).Transparency,...
        'Parent',tab5);
    tg_visible = uicontrol('Style','checkbox',...
        'Units','characters',...
        'Value',GColors.TimeGroups(index).Visible,...
        'Position',[54 pos(4)-offset 10 2],...
        'TooltipString','Visible on/off',...
        'UserData',GColors_default.TimeGroups(index).Visible,...
        'Parent',tab5);
    tg_string = uicontrol('Style','edit',...
        'Units','characters',...
        'String',GColors.TimeGroups(index).String,...
        'Position',[70 pos(4)-offset 20 2],...
        'BackgroundColor',panelColor,...
        'TooltipString','Must contain (...)',...
        'UserData',GColors_default.TimeGroups(index).String,...
        'Parent',tab5);
    tg_checked = uicontrol('Style','checkbox',...
        'Units','characters',...
        'Value',GColors.TimeGroups(index).Checked,...
        'Position',[92 pos(4)-offset 10 2],...
        'TooltipString','Affected on/off',...
        'UserData',GColors_default.TimeGroups(index).Checked,...
        'Parent',tab5);
    set(tg_color,'Callback',{@pickcolor_callback});
    set(tg_transp,'Callback',{@checkfloat_callback,GColors.atlas_transparency,'Transparency',0,1});
    % Storing
    all_tg_colors = [all_tg_colors;tg_color];
    all_tg_string = [all_tg_string;tg_string];
    all_tg_transp = [all_tg_transp;tg_transp];
    all_tg_checked = [all_tg_checked;tg_checked];
    all_tg_visible = [all_tg_visible;tg_visible];
end

end