function answer = modal_Preferences(data)
% Preferences Modal Menu

% Display Parameters
W = 100;
H = 25;
ftsize = 10;
panelColor = get(0,'DefaultUicontrolBackgroundColor');
answer = cell(2,1);

% getting data
str1 = data.str1;
str2 = data.str2;
str3 = data.str3;
str4 = data.str4;

% Creating Dialog Box
f2 = dialog('Units','characters',...
    'Position',[30 30 W H],...
    'HandleVisibility','callback',...
    'IntegerHandle','off',...
    'Renderer','painters',...
    'Toolbar','figure',...
    'NumberTitle','off',...
    'Name','Booting Options');

tab0 = uipanel('FontSize',ftsize,...
    'Units','characters',...
    'Position',[0 4 W H-4],...
    'Parent',f2);
pos = get(tab0,'Position');

% OK & CANCEL Buttons
okButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/4 1 W/4 2],...
    'String','OK',...
    'Parent',f2);

cancelButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/2 1 W/4 2],...
    'String','Cancel',...
    'Parent',f2);

set(okButton,'Callback',@okButton_callback);
set(cancelButton,'Callback', @cancelButton_callback);

    function cancelButton_callback(~,~)
        answer = [];
        close(f2);
    end

   function okButton_callback(~,~)
       answer{1} = e1.String;
       answer{2} = e2.String;
       close(f2);
   end

    function getdirButton_callback(~,~,edit)
        edit.String = uigetdir();
    end

% SEED directory - Editable text
h1 = 8;
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-h1-1 W-4 h1],...
    'String',str1,...
    'HorizontalAlignment','left',...
    'BackgroundColor','w',...
    'Parent',tab0);
e1 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',str2,...
    'Position',[2 pos(4)-h1-2-1.5 W-16 2],...
    'TooltipString','SEED',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
b1 = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'String','Browse',...
    'Position',[W-14 pos(4)-h1-2-1.5 13 2],...
    'TooltipString','Get Dir',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
% SEED_SPIKO - Editable text
h2=5;
uicontrol('Style','text',...
    'Units','characters',...
    'Position',[2 pos(4)-h1-h2-2-2.5 W-4 h2],...
    'String',str3,...
    'HorizontalAlignment','left',...
    'BackgroundColor','w',...
    'Parent',tab0);
e2 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',str4,...
    'Position',[2 pos(4)-h1-h2-7 W-16 2],...
    'TooltipString','SEED_SPIKO',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
b2 = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'String','Browse',...
    'Position',[W-14 pos(4)-h1-h2-7 13 2],...
    'TooltipString','Get Dir',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);

set(b1,'Callback', {@getdirButton_callback,e1});
set(b2,'Callback', {@getdirButton_callback,e2});

waitfor(f2);

end